### ISSUE TITLE
Handbook HTML issues

### ISSUE THREAD

**Issue by nwf** [cmukgb/ctfws-timer-android#5]
* The generated handbook HTML appears to be missing section references in prose.  (e.g. "In , , and ")
* Some anchors are generated apparently below the section heading they are meant to reference, so scrolling scrolls one line too far.

**Comment by timparenti** [comment]
We should also consider baking the generation/publication of the HTML rulebook into the main [ctfws](https://github.com/cmukgb/ctfws) app, since rule changes do occur from time to time, and this feature should not be dependent on having a recently-generated local version.

We would, however, almost certainly want to still cache the rulebook locally in some way. I'm not sure, though, of the best approach for that, given how late rule changes could conceivably be published.

**Comment by nwf** [comment]
That's fair enough.  I suppose the correct thing to do is to have the app download its resources and cache them locally.  There's hopefully some easy way to do that, that respects HTTP 304, on Android.

**Comment by nwf** [comment]
Hah, I just had maybe a better thought about the handbook caching... rather than polling the HTTP server, we could publish a timestamp & hash via MQTT.  Since we've already got a publish/subscribe system in place, why not use it? :smiling_imp:

**Comment by nwf** [comment]
I've taken some initial steps in this direction; https://github.com/cmukgb/ctfws-host-daemons/blob/master/inotifywait-handbook will do the server side, I've got a prototype of the generator that I'll push for review soon, and I'll re-work the app this weekend to pay attention to these things.

**Comment by nwf** [comment]
I think this one has been resolved with the shiny new download mechanism.

**Comment by timparenti** [comment]
> Some anchors are generated apparently below the section heading they are meant to reference, so scrolling scrolls one line too far.

I think that part is still outstanding, but it's technically more an issue with the marked-up source of the rules file in [cmukgb/ctfws](https://github.com/cmukgb/ctfws).  We don't have Issues open on the rules themselves, of course, so I'll make a note to take a look at that.
